#
# Default skills in ascending position order i.e., icon4, icon5, icon6, ...
#

ALL_ROLAND_SKILLS = [
    "gd_skills2_roland.support.impact",
    "gd_skills2_roland.infantry.sentry",
    "gd_skills2_roland.support.defense",
    "gd_skills2_roland.support.stockpile",
    "gd_skills2_roland.medic.fitness",
    "gd_skills2_roland.medic.aidstation",
    "gd_skills2_roland.infantry.scattershot",
    "gd_skills2_roland.infantry.metalstorm",
    "gd_skills2_roland.support.quickcharge",
    "gd_skills2_roland.support.barrage",
    "gd_skills2_roland.medic.overload",
    "gd_skills2_roland.medic.cauterize",
    "gd_skills2_roland.infantry.refire",
    "gd_skills2_roland.infantry.assault",
    "gd_skills2_roland.support.grenadier",
    "gd_skills2_roland.support.deploy",
    "gd_skills2_roland.medic.revive",
    "gd_skills2_roland.medic.grit",
    "gd_skills2_roland.infantry.guidedmissile",
    "gd_skills2_roland.support.supplydrop",
    "gd_skills2_roland.medic.stat",
]

ALL_MORDECAI_SKILLS = [
    "gd_skills2_mordecai.sniper.focus",
    "gd_skills2_mordecai.sniper.caliber",
    "gd_skills2_mordecai.rogue.swiftstrike",
    "gd_skills2_mordecai.rogue.swipe",
    "gd_skills2_mordecai.gunslinger.deadly",
    "gd_skills2_mordecai.gunslinger.guncrazy",
    "gd_skills2_mordecai.sniper.smirk",
    "gd_skills2_mordecai.sniper.killer",
    "gd_skills2_mordecai.rogue.fasthands",
    "gd_skills2_mordecai.rogue.outforblood",
    "gd_skills2_mordecai.gunslinger.lethalstrike",
    "gd_skills2_mordecai.gunslinger.riotousremedy",
    "gd_skills2_mordecai.sniper.loaded",
    "gd_skills2_mordecai.sniper.carrioncall",
    "gd_skills2_mordecai.rogue.aerialimpact",
    "gd_skills2_mordecai.rogue.ransack",
    "gd_skills2_mordecai.gunslinger.predator",
    "gd_skills2_mordecai.gunslinger.hairtrigger",
    "gd_skills2_mordecai.sniper.trespass",
    "gd_skills2_mordecai.rogue.birdofprey",
    "gd_skills2_mordecai.gunslinger.relentless",
]

ALL_LILITH_SKILLS = [
    "gd_skills2_lilith.controller.diva",
    "gd_skills2_lilith.controller.striking",
    "gd_skills2_lilith.elemental.quicksilver",
    "gd_skills2_lilith.elemental.spark",
    "gd_skills2_lilith.assassin.slayer",
    "gd_skills2_lilith.assassin.silentresolve",
    "gd_skills2_lilith.controller.innerglow",
    "gd_skills2_lilith.controller.dramaticentrance",
    "gd_skills2_lilith.elemental.resilience",
    "gd_skills2_lilith.elemental.radiance",
    "gd_skills2_lilith.assassin.enforcer",
    "gd_skills2_lilith.assassin.hitandrun",
    "gd_skills2_lilith.controller.hardtoget",
    "gd_skills2_lilith.controller.girlpower",
    "gd_skills2_lilith.elemental.venom",
    "gd_skills2_lilith.elemental.intuition",
    "gd_skills2_lilith.assassin.highvelocity",
    "gd_skills2_lilith.assassin.blackout",
    "gd_skills2_lilith.controller.mindgames",
    "gd_skills2_lilith.elemental.phoenix",
    "gd_skills2_lilith.assassin.phasestrike",
]

ALL_BRICK_SKILLS = [
    "gd_skills2_brick.brawler.ironfist",
    "gd_skills2_brick.brawler.endlessrage",
    "gd_skills2_brick.tank.hardened",
    "gd_skills2_brick.tank.safeguard",
    "gd_skills2_brick.tank.endowed",
    "gd_skills2_brick.blaster.rapidreload",
    "gd_skills2_brick.brawler.stinglikeabee",
    "gd_skills2_brick.brawler.heavyhanded",
    "gd_skills2_brick.tank.bash",
    "gd_skills2_brick.tank.juggernaut",
    "gd_skills2_brick.blaster.revenge",
    "gd_skills2_brick.blaster.wideload",
    "gd_skills2_brick.brawler.prizefighter",
    "gd_skills2_brick.brawler.shortfuse",
    "gd_skills2_brick.tank.payback",
    "gd_skills2_brick.tank.diehard",
    "gd_skills2_brick.blaster.liquidate",
    "gd_skills2_brick.blaster.castiron",
    "gd_skills2_brick.brawler.bloodsport",
    "gd_skills2_brick.tank.unbreakable",
    "gd_skills2_brick.blaster.masterblaster",
]

ACTION_SKILLS = [
    "gd_skills2_roland.action.a_deployscorpio",
    "gd_skills2_mordecai.action.a_launchbloodwing",
    "gd_skills2_lilith.action.a_phasewalk",
    "gd_skills2_brick.action.a_berserk",
]
