[project]
name = "custom_skill_trees"
version = "0.3"
authors = [{ name = "-Ry" }]
description = """Significantly alters how the skill tree interface is created allowing the composition of
any skill tree layout using the existing icon assets. While enabled this pulls the layout directly
from the player controller skill tree so is always in sync (assuming only existing skills are used).
"""

[tool.sdkmod]
name = "Custom Skill Trees"
supported_games = ["BL1"]
download = "https://raw.githubusercontent.com/Ry0511/my_bl1_sdk_mods/refs/heads/master/packaged/custom_skill_trees.sdkmod"
license = { name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
